[package]
name = "xml"
version = "1.0.0"
description = "A library for encoding and decoding XML"
repository = "https://github.com/edjcase/motoko_xml"
keywords = ["xml"]
license = "MIT"

[dependencies]
base = "0.14.9"
xtended-numbers = "0.4.0"
xtended-text = "1.0.0"

[dev-dependencies]
test = "2.1.1"
