[dependencies]
base = "0.11.1"
xtended-numbers = "0.3.1"
xtended-text = "0.2.5"

[package]
name = "xml"
version = "0.3.0"
description = "A library for encoding and decoding XML"
repository = "https://github.com/edjcase/motoko_xml"
keywords = [ "xml" ]
license = "MIT"

[dev-dependencies]
test = "2.0.0"