[package]
name = "xml"
version = "2.1.0"
description = "A library for encoding and decoding XML"
repository = "https://github.com/edjcase/motoko_xml"
keywords = ["xml", "encoding", "decoding", "parser", "serializer"]
license = "MIT"

[dependencies]
"core@1" = "1.0.0"
"xtended-numbers@2" = "2.1.0"
"buffer@0" = "0.1.0"

[dev-dependencies]
test = "2.1.1"
