name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install MOPS
        run: npm i -g ic-mops

      - name: Install Vessel
        run: sudo wget https://github.com/dfinity/vessel/releases/download/v0.6.4/vessel-linux64 -O /usr/bin/vessel

      - name: T
        run: sudo chmod +x /usr/bin/vessel

      - name: Install Wasmtime
        run: curl https://wasmtime.dev/install.sh -sSf | bash

      - name: Run Make
        run: make
