name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install MOPS
        run: npm i -g ic-mops

      - name: Download MOPS packages
        run: mops install

      - name: Run Tests
        run: make test
